# Generated by Django 3.2.3 on 2022-04-10 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applier_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('applier_phone', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('date_applied', models.DateTimeField(auto_now_add=True, verbose_name='Время заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(unique=True, verbose_name='Английское название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('on_main', models.BooleanField(default=False, verbose_name='Показать на главной странице')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Английское название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('on_main', models.BooleanField(default=False, verbose_name='Показать на главной странице')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=64, unique=True, verbose_name='Подкатегория')),
                ('slug', models.SlugField(unique=True, verbose_name='Английское название')),
                ('category_slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_slug', to='control.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Английское название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цена')),
                ('on_main', models.BooleanField(default=False, verbose_name='Показать на главной странице')),
                ('category_slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_slug_product', to='control.category', verbose_name='Категория')),
                ('subcategory_slug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_slug_product', to='control.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
